### ISSUE TITLE
MineSkin implementation

### ISSUE THREAD

**Issue by InventivetalentDev** [ProtocolSupport/ProtocolSupportPocketStuff#131]
So I've noticed a lot of requests coming from this project which are unsuccessful.  
Your current implementation completely ignores the delays returned by the API which are required since Mojang enforces delays to skin changes. I submitted https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/pull/130 to respect those delays.  

However, there is still one major issue: You are running the requests to MineSkin on multiple threads. This results in your requests essentially still ignoring the delays by constantly throwing more stuff at the API in turn leading to mostly unsuccessful generations.  
I'd recommend using https://github.com/InventivetalentDev/MineskinClient/blob/master/src/main/java/org/mineskin/MineskinClient.java or a similar implementation which only sends one request at a time after the returned delays.

**Comment by Shevchik** [comment]
This plugin is dead since MrPowerGamerBR left. I merged pull request, but this plugin is scheduled for removal when pspe rewrite completes.

**Comment by InventivetalentDev** [comment]
Alright. Please keep the stuff I mentioned in mind though if you intend on using mineskin in the rewrite.  

Also, would you mind me blocking requests coming from this? The amount of requests coming in is starting to affect overall API performance, so I might have to limit access.

**Comment by Shevchik** [comment]
Yeah, you can block it, i removed the mention of that feature. You may also create a pull request that removes the feature.

I only plan to provide an API that allows getting pe player client data, what developer gonna do with it is not my problem.

**Comment by magicus** [comment]
@InventivetalentDev I'm trying to resurrect the MineSkin implementation in PSPS. I will make sure we respect the delays, and use a single download thread. I will also use a persistent cache so I do not need to send the same skin twice to MineSkin. 

I discussed this with @Shevchik in our Discord, and there's a lingering doubt that we might still be flooding MineSkin, especially if PSPE gets used on large-scale servers in the future. Is there something I should think of to make sure we're being kind to your service? One of the approaches we have is that Shevchick is going to implement a MineSkin-esque feature built in, so if you have a large-scale operations you can supply your own mojang accounts for skin signing, instead of using MineSkin. I still want to keep the MineSkin approach though, for small family-sized PSPE installations (like the one I'm personally using).

**Comment by InventivetalentDev** [comment]
If your implementation respects the delays given by the API (and by Mojang) there shouldn't be any major issues with exhausting MineSkin, especially if you're using a local cache for the skin data.
Some base delay to the requests also helps just in case the API has internal issues so you don't keep flooding it with requests if it keeps returning errors.  

And while I get why larger servers might want to use their own accounts, I'd welcome the encouragement to use Mineskin anyway, since it does heavily depend on the number of available accounts :)
